//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]

namespace PS.Kiosk.Data
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class KioskDataEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new KioskDataEntities object using the connection string found in the 'KioskDataEntities' section of the application configuration file.
        /// </summary>
        public KioskDataEntities() : base("name=KioskDataEntities", "KioskDataEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new KioskDataEntities object.
        /// </summary>
        public KioskDataEntities(string connectionString) : base(connectionString, "KioskDataEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new KioskDataEntities object.
        /// </summary>
        public KioskDataEntities(EntityConnection connection) : base(connection, "KioskDataEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<tblParameters> tblParameters
        {
            get
            {
                if ((_tblParameters == null))
                {
                    _tblParameters = base.CreateObjectSet<tblParameters>("tblParameters");
                }
                return _tblParameters;
            }
        }
        private ObjectSet<tblParameters> _tblParameters;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<tblShetabError> tblShetabError
        {
            get
            {
                if ((_tblShetabError == null))
                {
                    _tblShetabError = base.CreateObjectSet<tblShetabError>("tblShetabError");
                }
                return _tblShetabError;
            }
        }
        private ObjectSet<tblShetabError> _tblShetabError;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<tblTransactions> tblTransactions
        {
            get
            {
                if ((_tblTransactions == null))
                {
                    _tblTransactions = base.CreateObjectSet<tblTransactions>("tblTransactions");
                }
                return _tblTransactions;
            }
        }
        private ObjectSet<tblTransactions> _tblTransactions;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<tblTransactionsReply> tblTransactionsReply
        {
            get
            {
                if ((_tblTransactionsReply == null))
                {
                    _tblTransactionsReply = base.CreateObjectSet<tblTransactionsReply>("tblTransactionsReply");
                }
                return _tblTransactionsReply;
            }
        }
        private ObjectSet<tblTransactionsReply> _tblTransactionsReply;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<tblReversalTrans> tblReversalTrans
        {
            get
            {
                if ((_tblReversalTrans == null))
                {
                    _tblReversalTrans = base.CreateObjectSet<tblReversalTrans>("tblReversalTrans");
                }
                return _tblReversalTrans;
            }
        }
        private ObjectSet<tblReversalTrans> _tblReversalTrans;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<tblSettleTrans> tblSettleTrans
        {
            get
            {
                if ((_tblSettleTrans == null))
                {
                    _tblSettleTrans = base.CreateObjectSet<tblSettleTrans>("tblSettleTrans");
                }
                return _tblSettleTrans;
            }
        }
        private ObjectSet<tblSettleTrans> _tblSettleTrans;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<tblSettleReversTrans> tblSettleReversTrans
        {
            get
            {
                if ((_tblSettleReversTrans == null))
                {
                    _tblSettleReversTrans = base.CreateObjectSet<tblSettleReversTrans>("tblSettleReversTrans");
                }
                return _tblSettleReversTrans;
            }
        }
        private ObjectSet<tblSettleReversTrans> _tblSettleReversTrans;

        #endregion
        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the tblParameters EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTotblParameters(tblParameters tblParameters)
        {
            base.AddObject("tblParameters", tblParameters);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the tblShetabError EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTotblShetabError(tblShetabError tblShetabError)
        {
            base.AddObject("tblShetabError", tblShetabError);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the tblTransactions EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTotblTransactions(tblTransactions tblTransactions)
        {
            base.AddObject("tblTransactions", tblTransactions);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the tblTransactionsReply EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTotblTransactionsReply(tblTransactionsReply tblTransactionsReply)
        {
            base.AddObject("tblTransactionsReply", tblTransactionsReply);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the tblReversalTrans EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTotblReversalTrans(tblReversalTrans tblReversalTrans)
        {
            base.AddObject("tblReversalTrans", tblReversalTrans);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the tblSettleTrans EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTotblSettleTrans(tblSettleTrans tblSettleTrans)
        {
            base.AddObject("tblSettleTrans", tblSettleTrans);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the tblSettleReversTrans EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTotblSettleReversTrans(tblSettleReversTrans tblSettleReversTrans)
        {
            base.AddObject("tblSettleReversTrans", tblSettleReversTrans);
        }

        #endregion
    }
    

    #endregion
    
    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="KioskDataModel", Name="tblParameters")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class tblParameters : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new tblParameters object.
        /// </summary>
        /// <param name="paramKey">Initial value of the ParamKey property.</param>
        public static tblParameters CreatetblParameters(global::System.String paramKey)
        {
            tblParameters tblParameters = new tblParameters();
            tblParameters.ParamKey = paramKey;
            return tblParameters;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String ParamKey
        {
            get
            {
                return _ParamKey;
            }
            set
            {
                if (_ParamKey != value)
                {
                    OnParamKeyChanging(value);
                    ReportPropertyChanging("ParamKey");
                    _ParamKey = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("ParamKey");
                    OnParamKeyChanged();
                }
            }
        }
        private global::System.String _ParamKey;
        partial void OnParamKeyChanging(global::System.String value);
        partial void OnParamKeyChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ParamValue
        {
            get
            {
                return _ParamValue;
            }
            set
            {
                OnParamValueChanging(value);
                ReportPropertyChanging("ParamValue");
                _ParamValue = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ParamValue");
                OnParamValueChanged();
            }
        }
        private global::System.String _ParamValue;
        partial void OnParamValueChanging(global::System.String value);
        partial void OnParamValueChanged();

        #endregion
    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="KioskDataModel", Name="tblReversalTrans")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class tblReversalTrans : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new tblReversalTrans object.
        /// </summary>
        /// <param name="id">Initial value of the ID property.</param>
        /// <param name="stan">Initial value of the Stan property.</param>
        /// <param name="tranRefNumber">Initial value of the TranRefNumber property.</param>
        /// <param name="cardNumber">Initial value of the CardNumber property.</param>
        /// <param name="primaryProcessCode">Initial value of the PrimaryProcessCode property.</param>
        /// <param name="primaryAmount">Initial value of the PrimaryAmount property.</param>
        /// <param name="primaryStan">Initial value of the PrimaryStan property.</param>
        /// <param name="primaryRefNumber">Initial value of the PrimaryRefNumber property.</param>
        /// <param name="primaryDateTime">Initial value of the PrimaryDateTime property.</param>
        /// <param name="primaryNewAmount">Initial value of the PrimaryNewAmount property.</param>
        /// <param name="sendDateTime">Initial value of the SendDateTime property.</param>
        /// <param name="isoTrack">Initial value of the IsoTrack property.</param>
        /// <param name="isInTry">Initial value of the IsInTry property.</param>
        public static tblReversalTrans CreatetblReversalTrans(global::System.Int64 id, global::System.String stan, global::System.String tranRefNumber, global::System.String cardNumber, global::System.String primaryProcessCode, global::System.String primaryAmount, global::System.String primaryStan, global::System.String primaryRefNumber, global::System.String primaryDateTime, global::System.String primaryNewAmount, global::System.DateTime sendDateTime, global::System.String isoTrack, global::System.Boolean isInTry)
        {
            tblReversalTrans tblReversalTrans = new tblReversalTrans();
            tblReversalTrans.ID = id;
            tblReversalTrans.Stan = stan;
            tblReversalTrans.TranRefNumber = tranRefNumber;
            tblReversalTrans.CardNumber = cardNumber;
            tblReversalTrans.PrimaryProcessCode = primaryProcessCode;
            tblReversalTrans.PrimaryAmount = primaryAmount;
            tblReversalTrans.PrimaryStan = primaryStan;
            tblReversalTrans.PrimaryRefNumber = primaryRefNumber;
            tblReversalTrans.PrimaryDateTime = primaryDateTime;
            tblReversalTrans.PrimaryNewAmount = primaryNewAmount;
            tblReversalTrans.SendDateTime = sendDateTime;
            tblReversalTrans.IsoTrack = isoTrack;
            tblReversalTrans.IsInTry = isInTry;
            return tblReversalTrans;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Int64 _ID;
        partial void OnIDChanging(global::System.Int64 value);
        partial void OnIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Stan
        {
            get
            {
                return _Stan;
            }
            set
            {
                OnStanChanging(value);
                ReportPropertyChanging("Stan");
                _Stan = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Stan");
                OnStanChanged();
            }
        }
        private global::System.String _Stan;
        partial void OnStanChanging(global::System.String value);
        partial void OnStanChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String TranRefNumber
        {
            get
            {
                return _TranRefNumber;
            }
            set
            {
                OnTranRefNumberChanging(value);
                ReportPropertyChanging("TranRefNumber");
                _TranRefNumber = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("TranRefNumber");
                OnTranRefNumberChanged();
            }
        }
        private global::System.String _TranRefNumber;
        partial void OnTranRefNumberChanging(global::System.String value);
        partial void OnTranRefNumberChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String CardNumber
        {
            get
            {
                return _CardNumber;
            }
            set
            {
                OnCardNumberChanging(value);
                ReportPropertyChanging("CardNumber");
                _CardNumber = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("CardNumber");
                OnCardNumberChanged();
            }
        }
        private global::System.String _CardNumber;
        partial void OnCardNumberChanging(global::System.String value);
        partial void OnCardNumberChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String PrimaryProcessCode
        {
            get
            {
                return _PrimaryProcessCode;
            }
            set
            {
                OnPrimaryProcessCodeChanging(value);
                ReportPropertyChanging("PrimaryProcessCode");
                _PrimaryProcessCode = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("PrimaryProcessCode");
                OnPrimaryProcessCodeChanged();
            }
        }
        private global::System.String _PrimaryProcessCode;
        partial void OnPrimaryProcessCodeChanging(global::System.String value);
        partial void OnPrimaryProcessCodeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String PrimaryAmount
        {
            get
            {
                return _PrimaryAmount;
            }
            set
            {
                OnPrimaryAmountChanging(value);
                ReportPropertyChanging("PrimaryAmount");
                _PrimaryAmount = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("PrimaryAmount");
                OnPrimaryAmountChanged();
            }
        }
        private global::System.String _PrimaryAmount;
        partial void OnPrimaryAmountChanging(global::System.String value);
        partial void OnPrimaryAmountChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String PrimaryStan
        {
            get
            {
                return _PrimaryStan;
            }
            set
            {
                OnPrimaryStanChanging(value);
                ReportPropertyChanging("PrimaryStan");
                _PrimaryStan = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("PrimaryStan");
                OnPrimaryStanChanged();
            }
        }
        private global::System.String _PrimaryStan;
        partial void OnPrimaryStanChanging(global::System.String value);
        partial void OnPrimaryStanChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String PrimaryRefNumber
        {
            get
            {
                return _PrimaryRefNumber;
            }
            set
            {
                OnPrimaryRefNumberChanging(value);
                ReportPropertyChanging("PrimaryRefNumber");
                _PrimaryRefNumber = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("PrimaryRefNumber");
                OnPrimaryRefNumberChanged();
            }
        }
        private global::System.String _PrimaryRefNumber;
        partial void OnPrimaryRefNumberChanging(global::System.String value);
        partial void OnPrimaryRefNumberChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String PrimaryDateTime
        {
            get
            {
                return _PrimaryDateTime;
            }
            set
            {
                OnPrimaryDateTimeChanging(value);
                ReportPropertyChanging("PrimaryDateTime");
                _PrimaryDateTime = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("PrimaryDateTime");
                OnPrimaryDateTimeChanged();
            }
        }
        private global::System.String _PrimaryDateTime;
        partial void OnPrimaryDateTimeChanging(global::System.String value);
        partial void OnPrimaryDateTimeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String PrimaryNewAmount
        {
            get
            {
                return _PrimaryNewAmount;
            }
            set
            {
                OnPrimaryNewAmountChanging(value);
                ReportPropertyChanging("PrimaryNewAmount");
                _PrimaryNewAmount = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("PrimaryNewAmount");
                OnPrimaryNewAmountChanged();
            }
        }
        private global::System.String _PrimaryNewAmount;
        partial void OnPrimaryNewAmountChanging(global::System.String value);
        partial void OnPrimaryNewAmountChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime SendDateTime
        {
            get
            {
                return _SendDateTime;
            }
            set
            {
                OnSendDateTimeChanging(value);
                ReportPropertyChanging("SendDateTime");
                _SendDateTime = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("SendDateTime");
                OnSendDateTimeChanged();
            }
        }
        private global::System.DateTime _SendDateTime;
        partial void OnSendDateTimeChanging(global::System.DateTime value);
        partial void OnSendDateTimeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String IsoTrack
        {
            get
            {
                return _IsoTrack;
            }
            set
            {
                OnIsoTrackChanging(value);
                ReportPropertyChanging("IsoTrack");
                _IsoTrack = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("IsoTrack");
                OnIsoTrackChanged();
            }
        }
        private global::System.String _IsoTrack;
        partial void OnIsoTrackChanging(global::System.String value);
        partial void OnIsoTrackChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.Byte[] PinBlock
        {
            get
            {
                return StructuralObject.GetValidValue(_PinBlock);
            }
            set
            {
                OnPinBlockChanging(value);
                ReportPropertyChanging("PinBlock");
                _PinBlock = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("PinBlock");
                OnPinBlockChanged();
            }
        }
        private global::System.Byte[] _PinBlock;
        partial void OnPinBlockChanging(global::System.Byte[] value);
        partial void OnPinBlockChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean IsInTry
        {
            get
            {
                return _IsInTry;
            }
            set
            {
                OnIsInTryChanging(value);
                ReportPropertyChanging("IsInTry");
                _IsInTry = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IsInTry");
                OnIsInTryChanged();
            }
        }
        private global::System.Boolean _IsInTry;
        partial void OnIsInTryChanging(global::System.Boolean value);
        partial void OnIsInTryChanged();

        #endregion
    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="KioskDataModel", Name="tblSettleReversTrans")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class tblSettleReversTrans : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new tblSettleReversTrans object.
        /// </summary>
        /// <param name="id">Initial value of the ID property.</param>
        /// <param name="stan">Initial value of the Stan property.</param>
        /// <param name="tranRefNumber">Initial value of the TranRefNumber property.</param>
        /// <param name="cardNumber">Initial value of the CardNumber property.</param>
        /// <param name="primaryProcessCode">Initial value of the PrimaryProcessCode property.</param>
        /// <param name="primaryAmount">Initial value of the PrimaryAmount property.</param>
        /// <param name="primaryStan">Initial value of the PrimaryStan property.</param>
        /// <param name="primaryRefNumber">Initial value of the PrimaryRefNumber property.</param>
        /// <param name="primaryDateTime">Initial value of the PrimaryDateTime property.</param>
        /// <param name="primaryNewAmount">Initial value of the PrimaryNewAmount property.</param>
        /// <param name="sendDateTime">Initial value of the SendDateTime property.</param>
        /// <param name="isoTrack">Initial value of the IsoTrack property.</param>
        /// <param name="isInTry">Initial value of the IsInTry property.</param>
        /// <param name="serviceType">Initial value of the ServiceType property.</param>
        /// <param name="pinBlock">Initial value of the PinBlock property.</param>
        public static tblSettleReversTrans CreatetblSettleReversTrans(global::System.Int64 id, global::System.String stan, global::System.String tranRefNumber, global::System.String cardNumber, global::System.String primaryProcessCode, global::System.String primaryAmount, global::System.String primaryStan, global::System.String primaryRefNumber, global::System.String primaryDateTime, global::System.String primaryNewAmount, global::System.DateTime sendDateTime, global::System.String isoTrack, global::System.Boolean isInTry, global::System.Int32 serviceType, global::System.Byte[] pinBlock)
        {
            tblSettleReversTrans tblSettleReversTrans = new tblSettleReversTrans();
            tblSettleReversTrans.ID = id;
            tblSettleReversTrans.Stan = stan;
            tblSettleReversTrans.TranRefNumber = tranRefNumber;
            tblSettleReversTrans.CardNumber = cardNumber;
            tblSettleReversTrans.PrimaryProcessCode = primaryProcessCode;
            tblSettleReversTrans.PrimaryAmount = primaryAmount;
            tblSettleReversTrans.PrimaryStan = primaryStan;
            tblSettleReversTrans.PrimaryRefNumber = primaryRefNumber;
            tblSettleReversTrans.PrimaryDateTime = primaryDateTime;
            tblSettleReversTrans.PrimaryNewAmount = primaryNewAmount;
            tblSettleReversTrans.SendDateTime = sendDateTime;
            tblSettleReversTrans.IsoTrack = isoTrack;
            tblSettleReversTrans.IsInTry = isInTry;
            tblSettleReversTrans.ServiceType = serviceType;
            tblSettleReversTrans.PinBlock = pinBlock;
            return tblSettleReversTrans;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Int64 _ID;
        partial void OnIDChanging(global::System.Int64 value);
        partial void OnIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Stan
        {
            get
            {
                return _Stan;
            }
            set
            {
                OnStanChanging(value);
                ReportPropertyChanging("Stan");
                _Stan = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Stan");
                OnStanChanged();
            }
        }
        private global::System.String _Stan;
        partial void OnStanChanging(global::System.String value);
        partial void OnStanChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String TranRefNumber
        {
            get
            {
                return _TranRefNumber;
            }
            set
            {
                OnTranRefNumberChanging(value);
                ReportPropertyChanging("TranRefNumber");
                _TranRefNumber = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("TranRefNumber");
                OnTranRefNumberChanged();
            }
        }
        private global::System.String _TranRefNumber;
        partial void OnTranRefNumberChanging(global::System.String value);
        partial void OnTranRefNumberChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String CardNumber
        {
            get
            {
                return _CardNumber;
            }
            set
            {
                OnCardNumberChanging(value);
                ReportPropertyChanging("CardNumber");
                _CardNumber = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("CardNumber");
                OnCardNumberChanged();
            }
        }
        private global::System.String _CardNumber;
        partial void OnCardNumberChanging(global::System.String value);
        partial void OnCardNumberChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String PrimaryProcessCode
        {
            get
            {
                return _PrimaryProcessCode;
            }
            set
            {
                OnPrimaryProcessCodeChanging(value);
                ReportPropertyChanging("PrimaryProcessCode");
                _PrimaryProcessCode = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("PrimaryProcessCode");
                OnPrimaryProcessCodeChanged();
            }
        }
        private global::System.String _PrimaryProcessCode;
        partial void OnPrimaryProcessCodeChanging(global::System.String value);
        partial void OnPrimaryProcessCodeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String PrimaryAmount
        {
            get
            {
                return _PrimaryAmount;
            }
            set
            {
                OnPrimaryAmountChanging(value);
                ReportPropertyChanging("PrimaryAmount");
                _PrimaryAmount = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("PrimaryAmount");
                OnPrimaryAmountChanged();
            }
        }
        private global::System.String _PrimaryAmount;
        partial void OnPrimaryAmountChanging(global::System.String value);
        partial void OnPrimaryAmountChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String PrimaryStan
        {
            get
            {
                return _PrimaryStan;
            }
            set
            {
                OnPrimaryStanChanging(value);
                ReportPropertyChanging("PrimaryStan");
                _PrimaryStan = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("PrimaryStan");
                OnPrimaryStanChanged();
            }
        }
        private global::System.String _PrimaryStan;
        partial void OnPrimaryStanChanging(global::System.String value);
        partial void OnPrimaryStanChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String PrimaryRefNumber
        {
            get
            {
                return _PrimaryRefNumber;
            }
            set
            {
                OnPrimaryRefNumberChanging(value);
                ReportPropertyChanging("PrimaryRefNumber");
                _PrimaryRefNumber = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("PrimaryRefNumber");
                OnPrimaryRefNumberChanged();
            }
        }
        private global::System.String _PrimaryRefNumber;
        partial void OnPrimaryRefNumberChanging(global::System.String value);
        partial void OnPrimaryRefNumberChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String PrimaryDateTime
        {
            get
            {
                return _PrimaryDateTime;
            }
            set
            {
                OnPrimaryDateTimeChanging(value);
                ReportPropertyChanging("PrimaryDateTime");
                _PrimaryDateTime = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("PrimaryDateTime");
                OnPrimaryDateTimeChanged();
            }
        }
        private global::System.String _PrimaryDateTime;
        partial void OnPrimaryDateTimeChanging(global::System.String value);
        partial void OnPrimaryDateTimeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String PrimaryNewAmount
        {
            get
            {
                return _PrimaryNewAmount;
            }
            set
            {
                OnPrimaryNewAmountChanging(value);
                ReportPropertyChanging("PrimaryNewAmount");
                _PrimaryNewAmount = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("PrimaryNewAmount");
                OnPrimaryNewAmountChanged();
            }
        }
        private global::System.String _PrimaryNewAmount;
        partial void OnPrimaryNewAmountChanging(global::System.String value);
        partial void OnPrimaryNewAmountChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime SendDateTime
        {
            get
            {
                return _SendDateTime;
            }
            set
            {
                OnSendDateTimeChanging(value);
                ReportPropertyChanging("SendDateTime");
                _SendDateTime = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("SendDateTime");
                OnSendDateTimeChanged();
            }
        }
        private global::System.DateTime _SendDateTime;
        partial void OnSendDateTimeChanging(global::System.DateTime value);
        partial void OnSendDateTimeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String IsoTrack
        {
            get
            {
                return _IsoTrack;
            }
            set
            {
                OnIsoTrackChanging(value);
                ReportPropertyChanging("IsoTrack");
                _IsoTrack = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("IsoTrack");
                OnIsoTrackChanged();
            }
        }
        private global::System.String _IsoTrack;
        partial void OnIsoTrackChanging(global::System.String value);
        partial void OnIsoTrackChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean IsInTry
        {
            get
            {
                return _IsInTry;
            }
            set
            {
                OnIsInTryChanging(value);
                ReportPropertyChanging("IsInTry");
                _IsInTry = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IsInTry");
                OnIsInTryChanged();
            }
        }
        private global::System.Boolean _IsInTry;
        partial void OnIsInTryChanging(global::System.Boolean value);
        partial void OnIsInTryChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ServiceType
        {
            get
            {
                return _ServiceType;
            }
            set
            {
                OnServiceTypeChanging(value);
                ReportPropertyChanging("ServiceType");
                _ServiceType = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ServiceType");
                OnServiceTypeChanged();
            }
        }
        private global::System.Int32 _ServiceType;
        partial void OnServiceTypeChanging(global::System.Int32 value);
        partial void OnServiceTypeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Byte[] PinBlock
        {
            get
            {
                return StructuralObject.GetValidValue(_PinBlock);
            }
            set
            {
                OnPinBlockChanging(value);
                ReportPropertyChanging("PinBlock");
                _PinBlock = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("PinBlock");
                OnPinBlockChanged();
            }
        }
        private global::System.Byte[] _PinBlock;
        partial void OnPinBlockChanging(global::System.Byte[] value);
        partial void OnPinBlockChanged();

        #endregion
    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="KioskDataModel", Name="tblSettleTrans")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class tblSettleTrans : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new tblSettleTrans object.
        /// </summary>
        /// <param name="id">Initial value of the ID property.</param>
        /// <param name="stan">Initial value of the Stan property.</param>
        /// <param name="tranRefNumber">Initial value of the TranRefNumber property.</param>
        /// <param name="sendDateTime">Initial value of the SendDateTime property.</param>
        /// <param name="isInTry">Initial value of the IsInTry property.</param>
        public static tblSettleTrans CreatetblSettleTrans(global::System.Int64 id, global::System.String stan, global::System.String tranRefNumber, global::System.DateTime sendDateTime, global::System.Boolean isInTry)
        {
            tblSettleTrans tblSettleTrans = new tblSettleTrans();
            tblSettleTrans.ID = id;
            tblSettleTrans.Stan = stan;
            tblSettleTrans.TranRefNumber = tranRefNumber;
            tblSettleTrans.SendDateTime = sendDateTime;
            tblSettleTrans.IsInTry = isInTry;
            return tblSettleTrans;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Int64 _ID;
        partial void OnIDChanging(global::System.Int64 value);
        partial void OnIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Stan
        {
            get
            {
                return _Stan;
            }
            set
            {
                OnStanChanging(value);
                ReportPropertyChanging("Stan");
                _Stan = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Stan");
                OnStanChanged();
            }
        }
        private global::System.String _Stan;
        partial void OnStanChanging(global::System.String value);
        partial void OnStanChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String TranRefNumber
        {
            get
            {
                return _TranRefNumber;
            }
            set
            {
                OnTranRefNumberChanging(value);
                ReportPropertyChanging("TranRefNumber");
                _TranRefNumber = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("TranRefNumber");
                OnTranRefNumberChanged();
            }
        }
        private global::System.String _TranRefNumber;
        partial void OnTranRefNumberChanging(global::System.String value);
        partial void OnTranRefNumberChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime SendDateTime
        {
            get
            {
                return _SendDateTime;
            }
            set
            {
                OnSendDateTimeChanging(value);
                ReportPropertyChanging("SendDateTime");
                _SendDateTime = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("SendDateTime");
                OnSendDateTimeChanged();
            }
        }
        private global::System.DateTime _SendDateTime;
        partial void OnSendDateTimeChanging(global::System.DateTime value);
        partial void OnSendDateTimeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean IsInTry
        {
            get
            {
                return _IsInTry;
            }
            set
            {
                OnIsInTryChanging(value);
                ReportPropertyChanging("IsInTry");
                _IsInTry = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IsInTry");
                OnIsInTryChanged();
            }
        }
        private global::System.Boolean _IsInTry;
        partial void OnIsInTryChanging(global::System.Boolean value);
        partial void OnIsInTryChanged();

        #endregion
    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="KioskDataModel", Name="tblShetabError")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class tblShetabError : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new tblShetabError object.
        /// </summary>
        /// <param name="c_ShetabErrorCode_">Initial value of the C_ShetabErrorCode_ property.</param>
        /// <param name="c_ShetabErrorDes_">Initial value of the C_ShetabErrorDes_ property.</param>
        /// <param name="c_BankSN_">Initial value of the C_BankSN_ property.</param>
        public static tblShetabError CreatetblShetabError(global::System.Int16 c_ShetabErrorCode_, global::System.String c_ShetabErrorDes_, global::System.Int16 c_BankSN_)
        {
            tblShetabError tblShetabError = new tblShetabError();
            tblShetabError.C_ShetabErrorCode_ = c_ShetabErrorCode_;
            tblShetabError.C_ShetabErrorDes_ = c_ShetabErrorDes_;
            tblShetabError.C_BankSN_ = c_BankSN_;
            return tblShetabError;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int16 C_ShetabErrorCode_
        {
            get
            {
                return _C_ShetabErrorCode_;
            }
            set
            {
                if (_C_ShetabErrorCode_ != value)
                {
                    OnC_ShetabErrorCode_Changing(value);
                    ReportPropertyChanging("C_ShetabErrorCode_");
                    _C_ShetabErrorCode_ = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("C_ShetabErrorCode_");
                    OnC_ShetabErrorCode_Changed();
                }
            }
        }
        private global::System.Int16 _C_ShetabErrorCode_;
        partial void OnC_ShetabErrorCode_Changing(global::System.Int16 value);
        partial void OnC_ShetabErrorCode_Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String C_ShetabErrorDes_
        {
            get
            {
                return _C_ShetabErrorDes_;
            }
            set
            {
                OnC_ShetabErrorDes_Changing(value);
                ReportPropertyChanging("C_ShetabErrorDes_");
                _C_ShetabErrorDes_ = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("C_ShetabErrorDes_");
                OnC_ShetabErrorDes_Changed();
            }
        }
        private global::System.String _C_ShetabErrorDes_;
        partial void OnC_ShetabErrorDes_Changing(global::System.String value);
        partial void OnC_ShetabErrorDes_Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int16 C_BankSN_
        {
            get
            {
                return _C_BankSN_;
            }
            set
            {
                if (_C_BankSN_ != value)
                {
                    OnC_BankSN_Changing(value);
                    ReportPropertyChanging("C_BankSN_");
                    _C_BankSN_ = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("C_BankSN_");
                    OnC_BankSN_Changed();
                }
            }
        }
        private global::System.Int16 _C_BankSN_;
        partial void OnC_BankSN_Changing(global::System.Int16 value);
        partial void OnC_BankSN_Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String C_ShetabErrorDesEn_
        {
            get
            {
                return _C_ShetabErrorDesEn_;
            }
            set
            {
                OnC_ShetabErrorDesEn_Changing(value);
                ReportPropertyChanging("C_ShetabErrorDesEn_");
                _C_ShetabErrorDesEn_ = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("C_ShetabErrorDesEn_");
                OnC_ShetabErrorDesEn_Changed();
            }
        }
        private global::System.String _C_ShetabErrorDesEn_;
        partial void OnC_ShetabErrorDesEn_Changing(global::System.String value);
        partial void OnC_ShetabErrorDesEn_Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String C_ShetabErrorDesFin_
        {
            get
            {
                return _C_ShetabErrorDesFin_;
            }
            set
            {
                OnC_ShetabErrorDesFin_Changing(value);
                ReportPropertyChanging("C_ShetabErrorDesFin_");
                _C_ShetabErrorDesFin_ = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("C_ShetabErrorDesFin_");
                OnC_ShetabErrorDesFin_Changed();
            }
        }
        private global::System.String _C_ShetabErrorDesFin_;
        partial void OnC_ShetabErrorDesFin_Changing(global::System.String value);
        partial void OnC_ShetabErrorDesFin_Changed();

        #endregion
    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="KioskDataModel", Name="tblTransactions")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class tblTransactions : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new tblTransactions object.
        /// </summary>
        /// <param name="id">Initial value of the ID property.</param>
        /// <param name="stan">Initial value of the Stan property.</param>
        /// <param name="refrenceNumber">Initial value of the RefrenceNumber property.</param>
        /// <param name="messageType">Initial value of the MessageType property.</param>
        /// <param name="sendDateTime">Initial value of the SendDateTime property.</param>
        public static tblTransactions CreatetblTransactions(global::System.Int64 id, global::System.String stan, global::System.String refrenceNumber, global::System.String messageType, global::System.DateTime sendDateTime)
        {
            tblTransactions tblTransactions = new tblTransactions();
            tblTransactions.ID = id;
            tblTransactions.Stan = stan;
            tblTransactions.RefrenceNumber = refrenceNumber;
            tblTransactions.MessageType = messageType;
            tblTransactions.SendDateTime = sendDateTime;
            return tblTransactions;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Int64 _ID;
        partial void OnIDChanging(global::System.Int64 value);
        partial void OnIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Stan
        {
            get
            {
                return _Stan;
            }
            set
            {
                OnStanChanging(value);
                ReportPropertyChanging("Stan");
                _Stan = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Stan");
                OnStanChanged();
            }
        }
        private global::System.String _Stan;
        partial void OnStanChanging(global::System.String value);
        partial void OnStanChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String RefrenceNumber
        {
            get
            {
                return _RefrenceNumber;
            }
            set
            {
                OnRefrenceNumberChanging(value);
                ReportPropertyChanging("RefrenceNumber");
                _RefrenceNumber = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("RefrenceNumber");
                OnRefrenceNumberChanged();
            }
        }
        private global::System.String _RefrenceNumber;
        partial void OnRefrenceNumberChanging(global::System.String value);
        partial void OnRefrenceNumberChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String MessageType
        {
            get
            {
                return _MessageType;
            }
            set
            {
                OnMessageTypeChanging(value);
                ReportPropertyChanging("MessageType");
                _MessageType = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("MessageType");
                OnMessageTypeChanged();
            }
        }
        private global::System.String _MessageType;
        partial void OnMessageTypeChanging(global::System.String value);
        partial void OnMessageTypeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime SendDateTime
        {
            get
            {
                return _SendDateTime;
            }
            set
            {
                OnSendDateTimeChanging(value);
                ReportPropertyChanging("SendDateTime");
                _SendDateTime = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("SendDateTime");
                OnSendDateTimeChanged();
            }
        }
        private global::System.DateTime _SendDateTime;
        partial void OnSendDateTimeChanging(global::System.DateTime value);
        partial void OnSendDateTimeChanged();

        #endregion
    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="KioskDataModel", Name="tblTransactionsReply")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class tblTransactionsReply : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new tblTransactionsReply object.
        /// </summary>
        /// <param name="id">Initial value of the ID property.</param>
        /// <param name="tranReqID">Initial value of the TranReqID property.</param>
        /// <param name="stan">Initial value of the Stan property.</param>
        /// <param name="refrenceNumber">Initial value of the RefrenceNumber property.</param>
        /// <param name="messageType">Initial value of the MessageType property.</param>
        /// <param name="sendDateTime">Initial value of the SendDateTime property.</param>
        /// <param name="replyCode">Initial value of the ReplyCode property.</param>
        public static tblTransactionsReply CreatetblTransactionsReply(global::System.Int64 id, global::System.Int64 tranReqID, global::System.String stan, global::System.String refrenceNumber, global::System.String messageType, global::System.DateTime sendDateTime, global::System.Int32 replyCode)
        {
            tblTransactionsReply tblTransactionsReply = new tblTransactionsReply();
            tblTransactionsReply.ID = id;
            tblTransactionsReply.TranReqID = tranReqID;
            tblTransactionsReply.Stan = stan;
            tblTransactionsReply.RefrenceNumber = refrenceNumber;
            tblTransactionsReply.MessageType = messageType;
            tblTransactionsReply.SendDateTime = sendDateTime;
            tblTransactionsReply.ReplyCode = replyCode;
            return tblTransactionsReply;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Int64 _ID;
        partial void OnIDChanging(global::System.Int64 value);
        partial void OnIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 TranReqID
        {
            get
            {
                return _TranReqID;
            }
            set
            {
                OnTranReqIDChanging(value);
                ReportPropertyChanging("TranReqID");
                _TranReqID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("TranReqID");
                OnTranReqIDChanged();
            }
        }
        private global::System.Int64 _TranReqID;
        partial void OnTranReqIDChanging(global::System.Int64 value);
        partial void OnTranReqIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Stan
        {
            get
            {
                return _Stan;
            }
            set
            {
                OnStanChanging(value);
                ReportPropertyChanging("Stan");
                _Stan = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Stan");
                OnStanChanged();
            }
        }
        private global::System.String _Stan;
        partial void OnStanChanging(global::System.String value);
        partial void OnStanChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String RefrenceNumber
        {
            get
            {
                return _RefrenceNumber;
            }
            set
            {
                OnRefrenceNumberChanging(value);
                ReportPropertyChanging("RefrenceNumber");
                _RefrenceNumber = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("RefrenceNumber");
                OnRefrenceNumberChanged();
            }
        }
        private global::System.String _RefrenceNumber;
        partial void OnRefrenceNumberChanging(global::System.String value);
        partial void OnRefrenceNumberChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String MessageType
        {
            get
            {
                return _MessageType;
            }
            set
            {
                OnMessageTypeChanging(value);
                ReportPropertyChanging("MessageType");
                _MessageType = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("MessageType");
                OnMessageTypeChanged();
            }
        }
        private global::System.String _MessageType;
        partial void OnMessageTypeChanging(global::System.String value);
        partial void OnMessageTypeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime SendDateTime
        {
            get
            {
                return _SendDateTime;
            }
            set
            {
                OnSendDateTimeChanging(value);
                ReportPropertyChanging("SendDateTime");
                _SendDateTime = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("SendDateTime");
                OnSendDateTimeChanged();
            }
        }
        private global::System.DateTime _SendDateTime;
        partial void OnSendDateTimeChanging(global::System.DateTime value);
        partial void OnSendDateTimeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ReplyCode
        {
            get
            {
                return _ReplyCode;
            }
            set
            {
                OnReplyCodeChanging(value);
                ReportPropertyChanging("ReplyCode");
                _ReplyCode = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ReplyCode");
                OnReplyCodeChanged();
            }
        }
        private global::System.Int32 _ReplyCode;
        partial void OnReplyCodeChanging(global::System.Int32 value);
        partial void OnReplyCodeChanged();

        #endregion
    
    }

    #endregion
    
}
