//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a tool.
//     Runtime Version: 1.1.4322.2032
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------

using System;
using System.Resources;
using System.Reflection;



// -----------------------------------------------------------------------------
//  <autogeneratedinfo>
//      This code was generated by:
//        SR Resource Generator custom tool for VS.NET, by Martin Granell, Readify
// 
//      It contains classes defined from the contents of the resource file:
//        C:\Dev\Trx\Src\Framework\SR.resx
// 
//      Generated: Thursday, February 09, 2006 1:45 AM
//  </autogeneratedinfo>
// -----------------------------------------------------------------------------
namespace Fanap.Messaging
{
    
    
    internal class SR
    {
        
        internal static string BinaryMessageFieldExpected
        {
            get
            {
                return Keys.GetString(Keys.BinaryMessageFieldExpected);
            }
        }
        
        internal static string CantBeGreaterThanMaximumLength
        {
            get
            {
                return Keys.GetString(Keys.CantBeGreaterThanMaximumLength);
            }
        }
        
        internal static string CantBeLowerThanZero
        {
            get
            {
                return Keys.GetString(Keys.CantBeLowerThanZero);
            }
        }
        
        internal static string CantBeNegative
        {
            get
            {
                return Keys.GetString(Keys.CantBeNegative);
            }
        }
        
        internal static string CantFormatMessageHeader
        {
            get
            {
                return Keys.GetString(Keys.CantFormatMessageHeader);
            }
        }
        
        internal static string CantHandleParameterType
        {
            get
            {
                return Keys.GetString(Keys.CantHandleParameterType);
            }
        }
        
        internal static string CantParseInnerMessage
        {
            get
            {
                return Keys.GetString(Keys.CantParseInnerMessage);
            }
        }
        
        internal static string CantParseMessageHeader
        {
            get
            {
                return Keys.GetString(Keys.CantParseMessageHeader);
            }
        }
        
        internal static string CantParseMti
        {
            get
            {
                return Keys.GetString(Keys.CantParseMti);
            }
        }
        
        internal static string CantSetMti
        {
            get
            {
                return Keys.GetString(Keys.CantSetMti);
            }
        }
        
        internal static string ComponentIsNotABitmapField
        {
            get
            {
                return Keys.GetString(Keys.ComponentIsNotABitmapField);
            }
        }
        
        internal static string ComponentIsNotAField
        {
            get
            {
                return Keys.GetString(Keys.ComponentIsNotAField);
            }
        }
        
        internal static string ComponentIsNotAMessage
        {
            get
            {
                return Keys.GetString(Keys.ComponentIsNotAMessage);
            }
        }
        
        internal static string ComponentIsNotAMessagingComponent
        {
            get
            {
                return Keys.GetString(Keys.ComponentIsNotAMessagingComponent);
            }
        }
        
        internal static string ComponentIsNotAnISO8583Message
        {
            get
            {
                return Keys.GetString(Keys.ComponentIsNotAnISO8583Message);
            }
        }
        
        internal static string ComponentIsNotMessageHeader
        {
            get
            {
                return Keys.GetString(Keys.ComponentIsNotMessageHeader);
            }
        }
        
        internal static string FieldDoesntExists
        {
            get
            {
                return Keys.GetString(Keys.FieldDoesntExists);
            }
        }
        
        internal static string FieldMustBeABitmap
        {
            get
            {
                return Keys.GetString(Keys.FieldMustBeABitmap);
            }
        }
        
        internal static string InnerMessageFieldExpected
        {
            get
            {
                return Keys.GetString(Keys.InnerMessageFieldExpected);
            }
        }
        
        internal static string InsufficientData
        {
            get
            {
                return Keys.GetString(Keys.InsufficientData);
            }
        }
        
        internal static string InvalidDataConsumed
        {
            get
            {
                return Keys.GetString(Keys.InvalidDataConsumed);
            }
        }
        
        internal static string InvalidLength
        {
            get
            {
                return Keys.GetString(Keys.InvalidLength);
            }
        }
        
        internal static string InvalidPad
        {
            get
            {
                return Keys.GetString(Keys.InvalidPad);
            }
        }
        
        internal static string LengthEncoderRequired
        {
            get
            {
                return Keys.GetString(Keys.LengthEncoderRequired);
            }
        }
        
        internal static string MoreDataNeeded
        {
            get
            {
                return Keys.GetString(Keys.MoreDataNeeded);
            }
        }
        
        internal static string MtiFormatterRequired
        {
            get
            {
                return Keys.GetString(Keys.MtiFormatterRequired);
            }
        }
        
        internal static string MustBeGreaterThanMinimumValue
        {
            get
            {
                return Keys.GetString(Keys.MustBeGreaterThanMinimumValue);
            }
        }
        
        internal static string MustBeGreaterThanZero
        {
            get
            {
                return Keys.GetString(Keys.MustBeGreaterThanZero);
            }
        }
        
        internal static string MustBeLowerOrEqualToUpperFieldNumber
        {
            get
            {
                return Keys.GetString(Keys.MustBeLowerOrEqualToUpperFieldNumber);
            }
        }
        
        internal static string OutOfBound
        {
            get
            {
                return Keys.GetString(Keys.OutOfBound);
            }
        }
        
        internal static string StringHeaderExpected
        {
            get
            {
                return Keys.GetString(Keys.StringHeaderExpected);
            }
        }
        
        internal static string StringMessageFieldExpected
        {
            get
            {
                return Keys.GetString(Keys.StringMessageFieldExpected);
            }
        }
        
        internal static string TheCollectionIsEmpty
        {
            get
            {
                return Keys.GetString(Keys.TheCollectionIsEmpty);
            }
        }
        
        internal static string UnexpectedBiggerDataLength
        {
            get
            {
                return Keys.GetString(Keys.UnexpectedBiggerDataLength);
            }
        }
        
        internal static string UnexpectedLength
        {
            get
            {
                return Keys.GetString(Keys.UnexpectedLength);
            }
        }
        
        internal static string Between(int from, int to)
        {
            return Keys.GetString(Keys.Between, new object[] {
                        from,
                        to});
        }
        
        internal static string BetweenXAndYZReceived(int from, int to, int recv)
        {
            return Keys.GetString(Keys.BetweenXAndYZReceived, new object[] {
                        from,
                        to,
                        recv});
        }
        
        internal static string CantConvertFieldToProperty(int fieldNumber, string name)
        {
            return Keys.GetString(Keys.CantConvertFieldToProperty, new object[] {
                        fieldNumber,
                        name});
        }
        
        internal static string CantFormatField(int fieldNumber)
        {
            return Keys.GetString(Keys.CantFormatField, new object[] {
                        fieldNumber});
        }
        
        internal static string CantParseField(int fieldNumber)
        {
            return Keys.GetString(Keys.CantParseField, new object[] {
                        fieldNumber});
        }
        
        internal static string DecodedBitmap(int fieldNumber, string value)
        {
            return Keys.GetString(Keys.DecodedBitmap, new object[] {
                        fieldNumber,
                        value});
        }
        
        internal static string DecodedField(int fieldNumber, string value)
        {
            return Keys.GetString(Keys.DecodedField, new object[] {
                        fieldNumber,
                        value});
        }
        
        internal static string FieldMustBeBitmap(int fieldNumber)
        {
            return Keys.GetString(Keys.FieldMustBeBitmap, new object[] {
                        fieldNumber});
        }
        
        internal static string InsufficientDataMoreIsRequired(int length)
        {
            return Keys.GetString(Keys.InsufficientDataMoreIsRequired, new object[] {
                        length});
        }
        
        internal static string InvalidByteLengthDetected(System.Byte length)
        {
            return Keys.GetString(Keys.InvalidByteLengthDetected, new object[] {
                        length});
        }
        
        internal static string InvalidFieldNumberParameter(int from, int to)
        {
            return Keys.GetString(Keys.InvalidFieldNumberParameter, new object[] {
                        from,
                        to});
        }
        
        internal static string InvalidLengthDetected(int length)
        {
            return Keys.GetString(Keys.InvalidLengthDetected, new object[] {
                        length});
        }
        
        internal static string InvalidLengthType(int length)
        {
            return Keys.GetString(Keys.InvalidLengthType, new object[] {
                        length});
        }
        
        internal static string LessOrEqualToN(int length)
        {
            return Keys.GetString(Keys.LessOrEqualToN, new object[] {
                        length});
        }
        
        internal static string NonNumericValue(string value)
        {
            return Keys.GetString(Keys.NonNumericValue, new object[] {
                        value});
        }
        
        internal static string OnlyZeroToNAllowed(int length)
        {
            return Keys.GetString(Keys.OnlyZeroToNAllowed, new object[] {
                        length});
        }
        
        internal static string UnknownFieldFormatter(int fieldNumber)
        {
            return Keys.GetString(Keys.UnknownFieldFormatter, new object[] {
                        fieldNumber});
        }
        
        internal static string UnknownFormatter(int fieldNumber)
        {
            return Keys.GetString(Keys.UnknownFormatter, new object[] {
                        fieldNumber});
        }
        
        internal class Keys
        {
            
            static System.Resources.ResourceManager resourceManager = new System.Resources.ResourceManager(typeof(SR));
            
            internal const string Between = "Between";
            
            internal const string BetweenXAndYZReceived = "BetweenXAndYZReceived";
            
            internal const string BinaryMessageFieldExpected = "BinaryMessageFieldExpected";
            
            internal const string CantBeGreaterThanMaximumLength = "CantBeGreaterThanMaximumLength";
            
            internal const string CantBeLowerThanZero = "CantBeLowerThanZero";
            
            internal const string CantBeNegative = "CantBeNegative";
            
            internal const string CantConvertFieldToProperty = "CantConvertFieldToProperty";
            
            internal const string CantFormatField = "CantFormatField";
            
            internal const string CantFormatMessageHeader = "CantFormatMessageHeader";
            
            internal const string CantHandleParameterType = "CantHandleParameterType";
            
            internal const string CantParseField = "CantParseField";
            
            internal const string CantParseInnerMessage = "CantParseInnerMessage";
            
            internal const string CantParseMessageHeader = "CantParseMessageHeader";
            
            internal const string CantParseMti = "CantParseMti";
            
            internal const string CantSetMti = "CantSetMti";
            
            internal const string ComponentIsNotABitmapField = "ComponentIsNotABitmapField";
            
            internal const string ComponentIsNotAField = "ComponentIsNotAField";
            
            internal const string ComponentIsNotAMessage = "ComponentIsNotAMessage";
            
            internal const string ComponentIsNotAMessagingComponent = "ComponentIsNotAMessagingComponent";
            
            internal const string ComponentIsNotAnISO8583Message = "ComponentIsNotAnISO8583Message";
            
            internal const string ComponentIsNotMessageHeader = "ComponentIsNotMessageHeader";
            
            internal const string DecodedBitmap = "DecodedBitmap";
            
            internal const string DecodedField = "DecodedField";
            
            internal const string FieldDoesntExists = "FieldDoesntExists";
            
            internal const string FieldMustBeABitmap = "FieldMustBeABitmap";
            
            internal const string FieldMustBeBitmap = "FieldMustBeBitmap";
            
            internal const string InnerMessageFieldExpected = "InnerMessageFieldExpected";
            
            internal const string InsufficientData = "InsufficientData";
            
            internal const string InsufficientDataMoreIsRequired = "InsufficientDataMoreIsRequired";
            
            internal const string InvalidByteLengthDetected = "InvalidByteLengthDetected";
            
            internal const string InvalidDataConsumed = "InvalidDataConsumed";
            
            internal const string InvalidFieldNumberParameter = "InvalidFieldNumberParameter";
            
            internal const string InvalidLength = "InvalidLength";
            
            internal const string InvalidLengthDetected = "InvalidLengthDetected";
            
            internal const string InvalidLengthType = "InvalidLengthType";
            
            internal const string InvalidPad = "InvalidPad";
            
            internal const string LengthEncoderRequired = "LengthEncoderRequired";
            
            internal const string LessOrEqualToN = "LessOrEqualToN";
            
            internal const string MoreDataNeeded = "MoreDataNeeded";
            
            internal const string MtiFormatterRequired = "MtiFormatterRequired";
            
            internal const string MustBeGreaterThanMinimumValue = "MustBeGreaterThanMinimumValue";
            
            internal const string MustBeGreaterThanZero = "MustBeGreaterThanZero";
            
            internal const string MustBeLowerOrEqualToUpperFieldNumber = "MustBeLowerOrEqualToUpperFieldNumber";
            
            internal const string NonNumericValue = "NonNumericValue";
            
            internal const string OnlyZeroToNAllowed = "OnlyZeroToNAllowed";
            
            internal const string OutOfBound = "OutOfBound";
            
            internal const string StringHeaderExpected = "StringHeaderExpected";
            
            internal const string StringMessageFieldExpected = "StringMessageFieldExpected";
            
            internal const string TheCollectionIsEmpty = "TheCollectionIsEmpty";
            
            internal const string UnexpectedBiggerDataLength = "UnexpectedBiggerDataLength";
            
            internal const string UnexpectedLength = "UnexpectedLength";
            
            internal const string UnknownFieldFormatter = "UnknownFieldFormatter";
            
            internal const string UnknownFormatter = "UnknownFormatter";
            
            internal static string GetString(string key)
            {
                return resourceManager.GetString(key, Resources.CultureInfo);
            }
            
            internal static string GetString(string key, object[] args)
            {
                string msg = resourceManager.GetString(key, Resources.CultureInfo);
                msg = string.Format(msg, args);
                return msg;
            }
        }
    }
}
