//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.225
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PS.Kiosk.Framework.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PS.Kiosk.Framework.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;CustomError&gt;
        ///  &lt;CustomErrorTable&gt;
        ///    &lt;Code&gt;0&lt;/Code&gt;
        ///    &lt;Name&gt;Unable To Connect To DB&lt;/Name&gt;
        ///    &lt;Description&gt;امكان برقراري ارتباط با بانك اطلاعاتي وجود ندارد.&lt;/Description&gt;
        ///  &lt;/CustomErrorTable&gt;
        ///
        ///  &lt;CustomErrorTable&gt;
        ///    &lt;Code&gt;1&lt;/Code&gt;
        ///    &lt;Name&gt;Internal Exception&lt;/Name&gt;
        ///    &lt;Description&gt;امکان دريافت اطلاعات وجود ندارد.&lt;/Description&gt;
        ///  &lt;/CustomErrorTable&gt;
        ///
        ///  &lt;CustomErrorTable&gt;
        ///    &lt;Code&gt;2&lt;/Code&gt;
        ///    &lt;Name&gt;Could Not Retrive Data&lt;/Name&gt;
        ///    &lt;Descripti [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ErrorMessages {
            get {
                return ResourceManager.GetString("ErrorMessages", resourceCulture);
            }
        }
    }
}
